# Generated by Django 3.2.14 on 2022-07-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='name',
            new_name='name1',
        ),
    ]
